/*******************************************************
 文件：CPcSrcData.idl
 作者：
 描述：点云原始数据结构体
 版本：v1.0
 日期：2023-12-02
 *******************************************************/

#include "CDataBase.idl"

//点云点的结构体
@final
struct CPcPoint
{
    float                       fPointX;        // 点的x坐标值,单位m
    float                       fPointY;        // 点的y坐标值,单位m
    float                       fPointZ;        // 点的z坐标值,单位m
    float                       fIntensity;     // 点的强度值
};

//点云原始数据相关信息结构体
struct CLidarInfo
{
    octet                        ucLidarId;      //雷达编号
    octet                        ucPcSource;     //雷达数据来源：1：在线雷达输出；2：离线pcap文件；3：预留
    string                       strIp;          //雷达ip
    boolean                      bStatus;        //雷达数据来源：1：在线；2：离线
    double                       dLidarLon;      //雷达经度
    double                       dLidarLat;      //雷达纬度
    float                        fLidarNorthAngle; //雷达北向夹角
    unsigned short               usLineNum;      //雷达线束
};

//点云原始数据相关信息结构体，跟视频做时间匹配，使用该结构体即可
struct CPcSrcInfo : CDataBase
{
    octet                           ucLidarId;          //雷达编号
    sequence<CLidarInfo>            vecLidaInfo;        //雷达信息 
};

//点云原始数据结构体
struct CPcSrcData
{
    CPcSrcInfo         stSrcInfo;   // 点云数据的相关信息
    unsigned long      unPointNums; // 点数量
    sequence<CPcPoint> vecPoints;   // 点集
};

//点云原始数据结构体
struct CPcSrcDataBuf
{
    CPcSrcInfo      stSrcInfo;   // 点云数据的相关信息
    unsigned long   unPointNums; // 点数量
    sequence<octet> vecPoints;   // 序列化点云
};

//点云原始数据结构体
@final
struct CPcSrcDataFixedLength 
{
    //存放各个阶段各种数据的时间戳：ms
    //0:点云到机时间戳
    unsigned long long          ulBufTimeStamp[10];

    //存放各个阶段各种数据的时延
    unsigned long               ulBufDelay[10];

    //存放各个阶段各种数据的帧率
    float                       ulBufFps[10];

    unsigned long long          ulTimestampPub;      // 发送时间戳(测试中间件专用,测时延)
    unsigned long               unSeqPub;            // 发送序列号(测试中间件专用,测丢包)

    unsigned long     unFrameId;          //帧号
    octet             eDataType;          //数据类型

    unsigned long              unPointNums;        //点数量
    CPcPoint          fixedVecPoints[115200 * 4];  //点集
};

//雷达原始数据包结构体
struct CPcSingleData
{
    //一帧点云的原始数据包，每个元素都是1350字节的包数据转换成的string
    sequence<string>            vecPacketData;
};

//雷达原始数据包结构体
struct CPcSrcPacketData
{
    //存放各个阶段各种数据的时间戳：ms，从前往后依次是：
    //0.点云0度数据包的时间戳
    //预留
    unsigned long long          ulBufTimeStamp[10];

    //一帧点云的原始数据包，每个元素都是1350字节的包数据转换成的string
    sequence<CPcSingleData>            vecSingleData;
};